### ISSUE TITLE
Encountering illegal parameter value error with fit_aitchison.rs

### ISSUE THREAD

**Issue by benc347** [mooreryan/divnet-rs#12]
Hello,

I'm receiving an error when I attempt to run divnet-rs on the small test files (divnet-rs/test_files/small/). The error appears to be occurring in fit_aitchison.rs. 

I am working on a server using Red Hat Enterprise Linux 9.0 (Plow), and I cloned divnet-rs v0.2.1 from GitHub. The versions of the dependencies I'm using are GCC 12.2.0, OpenBLAS 0.3.23, and Rust 1.65.0. Compiling divnet-rs with `cargo build --release` succeeded without any errors (as best as I can tell).

Running `OPENBLAS_NUM_THREADS=1 RUST_LOG=debug target/release/divnet-rs test_files/small/config_small.toml` results in the following error message:

```
 OPENBLAS_NUM_THREADS=1 RUST_LOG=debug target/release/divnet-rs test_files/small/config_small.toml
[2023-08-09T17:12:55Z DEBUG divnet_rs] opts: Opts { config: "test_files/small/config_small.toml" }
[2023-08-09T17:12:55Z DEBUG divnet_rs] config: Config { model: FitAitchisonConfig { em_iter: 4, em_burn: 2, mc_iter: 300, mc_burn: 150, stepsize: 0.01, perturbation: 0.05, replicates: 5, base_taxa: 0 }, io: IoConfig { count_table: "./test_files/small/small_count_table.csv", sample_data: "./test_files/small/small_sample_data.csv", output: "./test_files/small/small_divnet_output.csv" }, misc: MiscConfig { random_seed: 0 } }
[2023-08-09T17:12:55Z DEBUG divnet_rs] otu_table: (5, 3)
[2023-08-09T17:12:55Z DEBUG divnet_rs] sample_data: (3, 1)
[2023-08-09T17:12:55Z INFO  divnet_rs] Running fit_aitchison
[2023-08-09T17:12:55Z DEBUG divnet_rs::fit_aitchison] Starting `fit_aitchison`
 ** On entry to DGELS  parameter number  1 had an illegal value
thread 'main' panicked at 'Failed to solve X_centered * B = Y_centered for B: "from dgels: the -1-th parameter had an illegal value"', src/fit_aitchison.rs:636:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running `cargo test` results in the following:

```
running 53 tests
test conversions::tests::output_matches_r::to_log_ratios_matches_r ... ok
test conversions::tests::output_matches_r::to_composition_matrix_matches_r ... ok
test conversions::tests::to_log_ratios_handles_zero_counts_in_base_taxa ... ok
test conversions::tests::to_log_ratios_handles_zero_counts_in_non_base_taxa ... ok
test conversions::tests::output_matches_r::you_get_the_correct_compositions_from_counts ... ok
test conversions::tests::to_log_ratios_works ... ok
test fit_aitchison::tests::diagonal_network_makes_diagonal_networks ... ok
 **On entry to DGELS  parameter number  6 had an illegal value
test fit_aitchison::tests::fit_aitchison_gives_reasonable_result ... FAILED
test fit_aitchison::tests::remove_at_returns_a_vec_without_idx ... ok
test fit_aitchison::tests::streaming_mean_panics_on_empty_array - should panic ... ok
test fit_aitchison::tests::streaming_mean_works ... ok
 **On entry to DGELS  parameter number 10 had an illegal value
test fit_aitchison::tests::fit_aitchison_gives_reasonable_result2 ... FAILED
test matrix::ewise::tests::map_maps_a_fn_onto_a_vec ... ok
test matrix::ewise::tests::test_add ... ok
test matrix::ewise::tests::test_div ... ok
test matrix::ewise::tests::test_ln ... ok
test matrix::ewise::tests::sum_sums_elements ... ok
test matrix::ewise::tests::test_mul ... ok
test matrix::ewise::tests::test_sub ... ok
test matrix::ewise::tests::zipmap_panics_if_vecs_are_different_lengths - should panic ... ok
test matrix::ewise::tests::zipmap_maps_a_fn_onto_two_vecs_lockstep ... ok
test matrix::tests::center_centers_rows_by_mean ... ok
test matrix::tests::col_returns_a_column_slice ... ok
test matrix::tests::center_centers_cols_by_mean ... ok
test matrix::tests::col_sums_sums_colss ... ok
test matrix::tests::covariance_gets_cov_matrix ... ok
test matrix::tests::covariance_gets_covariance_of_two_slices ... ok
test matrix::tests::diag_gets_elements_on_the_diagonal ... ok
test matrix::tests::colmeans_gets_column_means ... ok
test matrix::tests::element_wise_ops1::exp_does_element_wise_exp ... ok
test matrix::tests::element_wise_ops1::ln_does_element_wise_natural_log ... ok
test matrix::tests::element_wise_ops2::eadd_does_elementwise_addition ... ok
test matrix::tests::element_wise_ops2::ediv_does_elementwise_division ... ok
test matrix::tests::element_wise_ops2::emul_does_elementwise_multiplication ... ok
test matrix::tests::element_wise_ops2::esub_does_elementwise_subtraction ... ok
test matrix::tests::equality::approx_eq_checks_equality_within_tolerance ... ok
test matrix::tests::equality::eq_checks_equality ... ok
test matrix::tests::get_gets_elements ... ok
test matrix::tests::get_unchecked_gets_elements_without_bounds_checking ... ok
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/work/LAS/sse-lab/Ben/Elk_16S/test/divnet-rs/target/debug/deps/divnet_rs-cee3e6d1de1be587` (signal: 11, SIGSEGV: invalid memory reference)
```
Based on these, it looks like there is some issue with running fit_aitchison.rs. Is it possible that there is an issue with a dependency or with my installation that would be causing this? Any help would be appreciated. Thanks!

**UPDATE: 8-10-23**

I created a conda environment with the dependencies from conda-forge (GCC 13.1.0, OpenBLAS 0.3.23, and Rust 1.71.1). After cloning and compiling divnet-rs v 0.2.1 into this environment, I was able to successfully run divnet-rs on the small test files. Running `cargo test` also succeeded with no failures. Based on this, I'm guessing there was a problem in my previous attempt with my dependencies and/or my divnet-rs installation on the server.

Feel free to mark this issue closed. Thanks!

**Comment by mooreryan** [comment]
Hey thanks for the bug report and the update, glad that worked for you.

If you have a moment, could you install divnet-rs from the git repository branch [issue-#12](https://github.com/mooreryan/divnet-rs/tree/issue-%2312)?  Once that is installed run divnet-rs like this:

```
RUST_BACKTRACE=1 OPENBLAS_NUM_THREADS=1 RUST_LOG=trace target/release/divnet-rs test_files/small/config_small.toml
```

That will turn on the backtrace as well as detailed tracing...I added a few extra statements in there on that branch.  My guess is that you are right and there is something odd going on with the deps with how you originally installed it.

(But since it is working for you now, don't feel like you have to do that.)

---

Also, off topic for this issue but, this has just reminded me that I didn't do a new release for `0.3.0` on github, but that has much improved performance over `0.2.1`, if you want to try the main branch.

**Comment by benc347** [comment]
Thanks for the quick reply! I went ahead and installed from the issue-#12 branch, and compiling proceeded without issue like before. Dependencies are still the same versions as those used previously. 

I ran divnet-rs with the backtrace as you suggested and got the following:
```
[2023-08-10T16:14:49Z DEBUG divnet_rs] opts: Opts { config: "test_files/small/config_small.toml" }
[2023-08-10T16:14:49Z DEBUG divnet_rs] config: Config { model: FitAitchisonConfig { em_iter: 4, em_burn: 2, mc_iter: 300, mc_burn: 150, stepsize: 0.01, perturbation: 0.05, replicates: 5, base_taxa: 0 }, io: IoConfig { count_table: "./test_files/small/small_count_table.csv", sample_data: "./test_files/small/small_sample_data.csv", output: "./test_files/small/small_divnet_output.csv" }, misc: MiscConfig { random_seed: 0 } }
[2023-08-10T16:14:49Z DEBUG divnet_rs] otu_table: (5, 3)
[2023-08-10T16:14:49Z DEBUG divnet_rs] sample_data: (3, 1)
[2023-08-10T16:14:49Z INFO  divnet_rs] Running fit_aitchison
[2023-08-10T16:14:49Z DEBUG divnet_rs::fit_aitchison] Starting `fit_aitchison`
[2023-08-10T16:14:49Z TRACE divnet_rs::matrix] before workspace query: trans: 78, m: 3, n: 1, nrhs: 4, lda: 3, ldb: 3, lwork: -1, info: 0, alen: 3, blen: 12
 ** On entry to DGELS  parameter number  3 had an illegal value
thread 'main' panicked at 'Failed to solve X_centered * B = Y_centered for B: "from dgels: the -3-th parameter had an illegal value"', src/fit_aitchison.rs:516:14
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: divnet_rs::fit_aitchison::get_b
   4: divnet_rs::fit_aitchison::fit_aitchison
   5: divnet_rs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)
```
I see that I'm getting the same "Failed to solve X_centered * B = Y_centered for B" error as I did previously. This time parameter 3 is what is flagged as illegal vs parameter 1, but I'm not sure if that matters or not. Let me know if there's anything else you'd like me to run. 

Thanks for mentioning v0.3.0. I'll be sure to try that one in my conda environment.

**Comment by mooreryan** [comment]
> This time parameter 3 is what is flagged as illegal vs parameter 1

Hmm, yeah that is pretty odd that it flagged a different illegal parameter this time.  The other odd thing is that the line in the logs that starts with `before workspace query` is exactly the same in your run as in my run (which works).  And those are the parameters to the `DGELS` lapack function, and they look fine to me.

I'm pretty curious about what is going on here, but it will probably take a good amount of time tracking down stuff between different versions, and checking upstream in the blas/lapack, etc.  Just so I'm clear, the conda environment you set up is working for you?  If that solution is working for you, let's go with that solution.  Unfortunately, I don't have the time right now to dig into the actual cause of this weird behavior.

---

> Thanks for mentioning v0.3.0. I'll be sure to try that one in my conda environment.

(I will cut a release for this soon.)

**Comment by mooreryan** [comment]
Here is that release btw: https://github.com/mooreryan/divnet-rs/releases/tag/0.3.0

**Comment by benc347** [comment]
> Just so I'm clear, the conda environment you set up is working for you?

Yes, it's working fine for me. I was able to run divnet-rs for the small, wide, and long testing datasets without any issue, and I am currently in the process of running it on one of my real datasets. 

>  it will probably take a good amount of time tracking down stuff between different versions, and checking upstream in the blas/lapack, etc. 

No worries. The conda environment seems to get around the issue fine (whatever the problem actually is). Thanks for linking the release and for looking into this! I appreciate it.
